apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kubeframe-placementrule
  namespace: kubeframe
spec:
  clusterSelector:
    matchExpressions:
      - key: kubeframe
        operator: In
        values:
          - "true"
