---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeframe-registry
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    workload.openshift.io/allowed: management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator-operatorgroup
  namespace: kubeframe-registry
spec:
  targetNamespaces:
    - kubeframe-registry
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: kubeframe-registry
spec:
  channel: "stable-3.6"
  name: quay-operator
  source: kubeframe-catalog
  sourceNamespace: openshift-marketplace
