---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
 name: kubeframe-master-0
 namespace: spoke-cluster-1
 labels:
   nmstate_config_cluster_name: spoke-cluster-1
spec:
 config:
   interfaces:
     - name: eno4
       type: ethernet
       state: up
       ethernet:
         auto-negotiation: true
         duplex: full
         speed: 10000
       ipv4:
         enabled: true
         address:
           - ip: 192.168.20.10
             prefix-length: 24
       mtu: 1500
       mac-address: 'CHANGE_SPOKE-1-MASTER-0_ENO4_MAC'
     - name: eno1
       type: ethernet
       state: up
       ethernet:
         auto-negotiation: true
         duplex: full
         speed: 1000
       ipv4:
         enabled: true
         address:
           - ip: 192.168.7.10
             prefix-length: 24
       mtu: 1500
       mac-address: 'CHANGE_SPOKE-1-MASTER-0_ENO1_MAC'
   dns-resolver:
     config:
       server:
         - 192.168.1.239
   routes:
     config:
       - destination: 192.168.7.0/24
         next-hop-address: 192.168.7.1
         next-hop-interface: eno1
       - destination: 0.0.0.0/0
         next-hop-address: 192.168.20.1
         next-hop-interface: eno4
 interfaces:
   - name: "eno4"
     macAddress: 'CHANGE_SPOKE-1-MASTER-0_ENO4_MAC'
   - name: "eno1"
     macAddress: 'CHANGE_SPOKE-1-MASTER-0_ENO1_MAC'
---
apiVersion: v1
kind: Secret
metadata:
 name: 'kubeframe-master-0-bmc-secret'
 namespace: 'spoke-cluster-1'
type: Opaque
data:
 username: 'CHANGE_SPOKE-1-MASTER-0_BMC_USERNAME'
 password: 'CHANGE_SPOKE-1-MASTER-0_BMC_PASSWORD'
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
 name: 'kubeframe-master-0'
 namespace: 'spoke-cluster-1'
 labels:
   infraenvs.agent-install.openshift.io: 'assisted-infra-env'
 annotations:
   inspect.metal3.io: disabled
   bmac.agent-install.openshift.io/hostname: 'kubeframe-master-0'
spec:
 online: false
 bootMACAddress: 'CHANGE_SPOKE-1-MASTER-0_ENO1_MAC'
 rootDeviceHints:
   deviceName: /dev/sda
 bmc:
   disableCertificateVerification: true
   address: 'redfish-virtualmedia+https://192.168.10.12/redfish/v1/Systems/1'
   credentialsName: 'kubeframe-master-0-bmc-secret'
