---
apiVersion: v1
kind: Namespace
metadata:
  name: CHANGE_SPOKE_NAME
---
apiVersion: v1
kind: Secret
metadata:
  name: CHANGE_SPOKE_PULL_SECRET_NAME
  namespace: CHANGE_SPOKE_NAME
stringData:
  .dockerconfigjson: 'CHANGE_PULL_SECRET'
  type: kubernetes.io/dockerconfigjson
---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: CHANGE_SPOKE_NAME
  namespace: CHANGE_SPOKE_NAME
spec:
  clusterDeploymentRef:
    name: CHANGE_SPOKE_NAME
  imageSetRef:
    name: CHANGE_SPOKE_CLUSTERIMAGESET
  apiVIP: "CHANGE_SPOKE_API"
  ingressVIP: "CHANGE_SPOKE_INGRESS"
  networking:
    clusterNetwork:
      - cidr: "CHANGE_SPOKE_CLUSTER_NET_CIDR"
        hostPrefix: CHANGE_SPOKE_CLUSTER_NET_PREFIX
    serviceNetwork:
      - "CHANGE_SPOKE_CLUSTER_NET_CIDR"
  provisionRequirements:
    controlPlaneAgents: 3
  sshPublicKey: 'CHANGE_RSA_PUB_KEY'
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: CHANGE_SPOKE_NAME
  namespace: CHANGE_SPOKE_NAME
spec:
  baseDomain: kubeframe.local
  clusterName: CHANGE_SPOKE_NAME
  controlPlaneConfig:
    servingCertificates: {}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: CHANGE_SPOKE_NAME
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "CHANGE_SPOKE_NAME"
  pullSecretRef:
    name: CHANGE_SPOKE_PULL_SECRET_NAME
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: CHANGE_SPOKE_NAME
  namespace: CHANGE_SPOKE_NAME
spec:
  clusterName: CHANGE_SPOKE_NAME
  clusterNamespace: CHANGE_SPOKE_NAME
  clusterLabels:
    name: CHANGE_SPOKE_NAME
    cloud: Baremetal
  applicationManager:
    argocdCluster: false
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: CHANGE_SPOKE_NAME
  namespace: CHANGE_SPOKE_NAME
  labels:
    name: CHANGE_SPOKE_NAME
    kubeframe: "true"
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
 name: 'CHANGE_SPOKE_NAME'
 namespace: 'CHANGE_SPOKE_NAME'
spec:
 clusterRef:
   name: 'CHANGE_SPOKE_NAME'
   namespace: 'CHANGE_SPOKE_NAME'
 pullSecretRef:
   name: 'CHANGE_SPOKE_PULL_SECRET_NAME'
 nmStateConfigLabelSelector:
   matchLabels:
     nmstate_config_cluster_name: CHANGE_SPOKE_NAME
 sshAuthorizedKey: 'CHANGE_RSA_PUB_KEY'
