---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: ztpfw-registry
  name: ztpfw-registry
spec:
  port:
    targetPort: registry
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    name: ztpfw-registry
