apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: open-cluster-management
stringData:
  .dockerconfigjson: 'PULL_SECRET'
  type: kubernetes.io/dockerconfigjson
