---
apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: default
spec:
  targetNamespaces:
  - default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: default
  namespace: default
spec:
  channel: alpha
  name: kubernetes-default
  source: operatorhubio-catalog
  sourceNamespace: olm
