# Site settings
show_downloads: false
title: 'ZTP for Factory Workflows'
description: "Documents produced by Management Integration Team"
permalink: pretty
repository: rh-ecosystem-edge/ztp-pipeline-relocatable
baseurl: /ztp-pipeline-relocatable/
url: https://rh-ecosystem-edge.github.io

plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# Site settings
future: false

# Build settings
markdown: kramdown
type: website

exclude:
  - GUIDELINES.md
  - README.md
  - TODO.md
  - .history

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
