  
name: Build and Publish
on:
  push:
    branches: [main]

env:
  QUAY_USER: ${{ secrets.QUAY_ROBOT_USER }}
  QUAY_PASS: ${{ secrets.QUAY_ROBOT_TOKEN }}

jobs:
  build-and-push-container-images:
    name: Build Container images and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare env
        run: |
          sudo apt-get -y install podman
          mkdir -p ~/.docker

      - name: Login to Quay
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${#QUAY_USER}
          password: ${#QUAY_PASS}

      - name: Build and Push Pipeline Image
        id: build-pipe
        run: |
          cd ${{ github.workspace }}

          if [[ "${{ github.ref_name }}" == 'main' ]];then
            RELEASE=latest
          else
            RELEASE=${{ github.ref_name }}-${{ github.sha }}
          fi
          
          echo ">>>> Building Pipe Release"
          echo "Release: ${RELEASE}"
          echo "Image Branch: ${{ github.ref_name }}"
          echo "Git hash: ${{ github.sha }}"
          echo "User: ${#QUAY_USER}"
          echo "Pass: ${#QUAY_PASS}"
          echo ">>>>"

          RELEASE=${RELEASE} make pipe

      - name: Build and Push UI Image
        id: build-ui
        run: |
          cd ${{ github.workspace }}

          if [[ "${{ github.ref_name }}" == 'main' ]];then
            RELEASE=latest
          else
            RELEASE=${{ github.ref_name }}-${{ github.sha }}
          fi

          echo ">>>> Building UI Release"
          echo "Release: ${RELEASE}"
          echo "Image Branch: ${{ github.ref_name }}"
          echo "Git hash: ${{ github.sha }}"
          echo ">>>>"

          RELEASE=${RELEASE} make ui