name: deploy-ztp-relocatable
on:
  workflow_dispatch:
    inputs:
      OC_KUBECONFIG_PATH:
        description: 'Absolute path to kubeconfig file?'
        required: true
      RUNNER:
        description: 'Github Action Runner Tag'
        required: true


env:
  OC_KUBECONFIG_PATH: ${{github.event.inputs.OC_KUBECONFIG_PATH}}
  OC_OCP_VERSION: '4.9'
  OC_ACM_VERSION: '2.4'
  DEPLOY_ACM_DIR: deploy-acm
  DEPLOY_REGISTRY_DIR: deploy-disconnected-registry
  SHARED_DIR: shared-utils


jobs:
  preflight:
    runs-on: ${{github.event.inputs.RUNNER}}   #tag with your runner tag

    steps:
      - uses: actions/checkout@v2 # create a checkout (pull repository) in the runner working_dir (usually _work)
      - run: git pull origin ${GITHUB_REF##*/}

      - name: Verification
        run: |
          cd ${{env.SHARED_DIR}}
          ./verify_preflight.sh

  deploy-RHACM:  
    needs: preflight           # run in parallel with the other jobs
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy RHACM with AI  
        run: |
          cd ${{env.DEPLOY_ACM_DIR}}
          ./deploy.sh

  deploy-disconnected-registry:
    needs: preflight          # run in parallel with the other jobs       
    runs-on: ${{github.event.inputs.RUNNER}}
    steps:
      - name: Deploy Internal Disconnected Registry 
        run: |
          cd ${{env.DEPLOY_REGISTRY_DIR}}
          ./deploy.sh