name: deploy-ztp-relocatable
on:
  workflow_dispatch:
    inputs:
      OC_KUBECONFIG_PATH:
        description: 'Absolute path to kubeconfig file?'
        required: true
      RUNNER:
        description: 'Github Action Runner Tag'
        required: true


env:
  OC_KUBECONFIG_PATH: ${{github.event.inputs.OC_KUBECONFIG_PATH}}
  SHARED_DIR: shared-utils


jobs:
  preflight:
    runs-on: ${{github.event.inputs.RUNNER}}   #tag with your runner tag

    steps:
      - uses: actions/checkout@v2 # create a checkout (pull repository) in the runner working_dir (usually _work)
      - run: git pull origin ${GITHUB_REF##*/}

      - name: Verification
        run: |
          cd ${{env.SHARED_DIR}}
          ./verify.sh

