---
apiVersion: oauth.openshift.io/v1
grantMethod: auto
kind: OAuthClient
metadata:
  labels:
    app: ztpfw-ui
  name: ztpfwoauth
  namespace: $UI_NS
redirectURIs:
- $UI_APP_URL/login/callback
secret: ztpfwoauthsecret
